### ISSUE TITLE
RoR5のAPIモード使って書き直したい

### ISSUE THREAD

**Issue by yagi2** [yagi2/imas_api#24]
んだけど。

**Comment by yagi2** [comment]
[yagi2/imas_api_rails](https://github.com/yagi2/imas_api_rails)に置いたここに今後やっていく

**Comment by yagi2** [comment]
のでこっちのissue全部クローズする。
向こうに移すこともやらずに、向こうは向こうで開発中に出会ったissueを登録する。

**Comment by unasuke** [comment]
なるほど

**Comment by yagi2** [comment]
でもこっちのissueには割といろいろためになるやつとかが書いてあるので適宜参照って感じ。
