### ISSUE TITLE
サーバ反映への手順を自動化したい。

### ISSUE THREAD

**Issue by yagi2** [yagi2/imas_api#9]
その通り
これはとあるサーバ上で動いてて

サーバ以外の場所で編集->github push->TravisCIでテスト->テストが通ったら自分で動いてるサーバへsshしてgit pull
って手順のsshからgit pullまでを自動化したい。

サーバでTravisCIからのhookを受け取ってpull……？　できるのかな。

**Comment by unasuke** [comment]
git pullするのはこのリポジトリ？

**Comment by yagi2** [comment]
このリポジトリだよー。

**Comment by unasuke** [comment]
`Build #4 (6df4e17) of yagi2/imas_api@master by Itsuki Aoyagi passed in 0 min 57 sec`に合致する正規表現にマッチする発言がなされた場合にshell script走らせるhubot scriptなんて作れるのかな

**Comment by yagi2** [comment]
hubotからやっていくスタイルか……
でもhubotはherokuで動いててimas_apiは別の自鯖で動いてるからhubotからshell script走らせたところで難しそう。

**Comment by unasuke** [comment]
Travisでpassしたときに特定のscript走らせるのはできそう
http://qiita.com/oh_rusty_nail/items/157241b6cb5a304462fe

**Comment by yagi2** [comment]
http://qiita.com/oh_rusty_nail/items/157241b6cb5a304462fe#2-8
ここら辺かな。

ただどうやってTravisCIのテスト環境の中から別の鯖の中へ潜り込んでpullするのかが問題だ～。

**Comment by unasuke** [comment]
ぽい記事
http://neemzy.org/articles/deploy-to-your-own-server-through-ssh-with-travis-ci

**Comment by yagi2** [comment]
@unasuke++++++++++++++++++++++++
